[funtenna]
title = "펀샵 ─ 펀테나"
url = "https://www.funshop.co.kr/Story/FuntennaList"
entrySelector = "div.story_list ul li"
titleSelector = "dl dt"
linkSelector = "a"
contentSelector = "dd p.text"
dateSelector = "p.info2 span.data span:nth-child(2)"
dateFormat = "yyyy-MM-dd"
imageSelector = "a img.item.lazy"
waitForSelector = "div.story_list ul li"
onFail = "stale"

[funtenna_latest]
title = "펀샵 ─ 펀테나 ─ 최신"
url = "https://www.funshop.co.kr/Story/FuntennaList"
entrySelector = "div.story_list ul li"
titleSelector = "dl dt"
linkSelector = "a"
contentSelector = "span.data span:nth-child(1)"
dateSelector = "p.info2 span.data span:nth-child(2)"
dateFormat = "yyyy-MM-dd"
imageSelector = "a img.item.lazy"
waitForSelector = "div.story_list ul li"
onFail = "stale"

[funtenna_car]
title = "펀샵 ─ 펀테나 ─ 자동차/모터사이클"
url = "https://www.funshop.co.kr/Story/FuntennaList#page=1&categoryNo=1&order=0&keyword="
entrySelector = "div.story_list ul li"
titleSelector = "dl dt"
linkSelector = "a"
contentSelector = "dd p.text"
dateSelector = "p.info2 span.data span:nth-child(2)"
dateFormat = "yyyy-MM-dd"
imageSelector = "a img.item.lazy"
waitForSelector = "div.story_list ul li"
onFail = "stale"

[funtenna_pcmobile]
title = "펀샵 ─ 펀테나 ─ PC/모바일"
url = "https://www.funshop.co.kr/Story/FuntennaList#page=1&categoryNo=2&order=0&keyword="
entrySelector = "div.story_list ul li"
titleSelector = "dl dt"
linkSelector = "a"
contentSelector = "dd p.text"
dateSelector = "p.info2 span.data span:nth-child(2)"
dateFormat = "yyyy-MM-dd"
imageSelector = "a img.item.lazy"
waitForSelector = "div.story_list ul li"
onFail = "stale"

[funtenna_life]
title = "펀샵 ─ 펀테나 ─ 생활/주방"
url = "https://www.funshop.co.kr/Story/FuntennaList#page=1&categoryNo=3&order=0&keyword="
entrySelector = "div.story_list ul li"
titleSelector = "dl dt"
linkSelector = "a"
contentSelector = "dd p.text"
dateSelector = "p.info2 span.data span:nth-child(2)"
dateFormat = "yyyy-MM-dd"
imageSelector = "a img.item.lazy"
waitForSelector = "div.story_list ul li"
onFail = "stale"

[funtenna_sports]
title = "펀샵 ─ 펀테나 ─ 아웃도어/스포츠"
url = "https://www.funshop.co.kr/Story/FuntennaList#page=1&categoryNo=4&order=0&keyword="
entrySelector = "div.story_list ul li"
titleSelector = "dl dt"
linkSelector = "a"
contentSelector = "dd p.text"
dateSelector = "p.info2 span.data span:nth-child(2)"
dateFormat = "yyyy-MM-dd"
imageSelector = "a img.item.lazy"
waitForSelector = "div.story_list ul li"
onFail = "stale"

[funtenna_trend]
title = "펀샵 ─ 펀테나 ─ 트렌드"
url = "https://www.funshop.co.kr/Story/FuntennaList#page=1&categoryNo=5&order=0&keyword="
entrySelector = "div.story_list ul li"
titleSelector = "dl dt"
linkSelector = "a"
contentSelector = "dd p.text"
dateSelector = "p.info2 span.data span:nth-child(2)"
dateFormat = "yyyy-MM-dd"
imageSelector = "a img.item.lazy"
waitForSelector = "div.story_list ul li"
onFail = "stale"

[funtenna_tech]
title = "펀샵 ─ 펀테나 ─ 미래기술"
url = "https://www.funshop.co.kr/Story/FuntennaList#page=1&categoryNo=6&order=0&keyword="
entrySelector = "div.story_list ul li"
titleSelector = "dl dt"
linkSelector = "a"
contentSelector = "dd p.text"
dateSelector = "p.info2 span.data span:nth-child(2)"
dateFormat = "yyyy-MM-dd"
imageSelector = "a img.item.lazy"
waitForSelector = "div.story_list ul li"
onFail = "stale"

[funtenna_fashion]
title = "펀샵 ─ 펀테나 ─ 패션/시계/가방"
url = "https://www.funshop.co.kr/Story/FuntennaList#page=1&categoryNo=7&order=0&keyword="
entrySelector = "div.story_list ul li"
titleSelector = "dl dt"
linkSelector = "a"
contentSelector = "dd p.text"
dateSelector = "p.info2 span.data span:nth-child(2)"
dateFormat = "yyyy-MM-dd"
imageSelector = "a img.item.lazy"
waitForSelector = "div.story_list ul li"
onFail = "stale"

[funtenna_hobby]
title = "펀샵 ─ 펀테나 ─ 취미/기타"
url = "https://www.funshop.co.kr/Story/FuntennaList#page=1&categoryNo=8&order=0&keyword="
entrySelector = "div.story_list ul li"
titleSelector = "dl dt"
linkSelector = "a"
contentSelector = "dd p.text"
dateSelector = "p.info2 span.data span:nth-child(2)"
dateFormat = "yyyy-MM-dd"
imageSelector = "a img.item.lazy"
waitForSelector = "div.story_list ul li"
onFail = "stale"

[funtenna_story]
title = "펀샵 ─ 펀테나 ─ 스토리"
url = "https://www.funshop.co.kr/Story/StoryList#page=1"
entrySelector = "div.story_content div.story_list ul li"
titleSelector = "dl dt"
linkSelector = "a.cover"
contentSelector = "dd p.text"
imageSelector = "img.item.lazy"
waitForSelector = "div.story_list ul li"
onFail = "stale"
